spring:
  mvc:
    hidden-method:
      filter:
        enabled: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dressshop?serverTimezone=Asia/Seoul
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database-platform:
    open-in-view: false

  messages:
    basename: messages, errors

  servlet:
    multipart:
      max-file-size: 20MB  #파일 한 개당 최대 용량
      max-request-size: 100MB  #요청당 최대 파일 크기
      location: C:\Project\image_file

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 804487516308-c4fcsciqbhnmhhumif0vl7fhq821hdif.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace

server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

uploadPath: C:\Project\resource